=== smartKaisar/smart-cms/api-modules/content-api-impl/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
targetNamespace="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
>
  <xs:simpleType name="smartDate">
    <xs:restriction base="xs:dateTime">
      <xs:pattern value="[1-9][0-9]{3}-[0-9]{2}-[0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]([+-][0-2][0-9]:[0-5][0-9])"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="mimeType" type="xs:string" />
  <xs:element name="name" type="xs:string" />
  <xs:element name="displayName" type="xs:string"/>
  <xs:element name="default" type="xs:string" />
  <xs:element name="typeNS" type="xs:string" />
  <xs:element name="typeName" type="xs:string" />
  <xs:element name="workspaceNS" type="xs:string" />
  <xs:element name="workspaceName" type="xs:string" />
  <xs:complexType name="workspaceDef">
    <xs:sequence>
      <xs:element ref="workspaceNS" minOccurs="1" maxOccurs="1" />
      <xs:element ref="workspaceName" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="workspace" type="workspaceDef" />
  <xs:complexType name="contentPointer">
    <xs:sequence>
      <xs:element ref="workspace" minOccurs="0" maxOccurs="1" />
      <xs:element ref="typeNS" minOccurs="1" maxOccurs="1" />
      <xs:element ref="typeName" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="definition" type="contentPointer" />
  <xs:element name="bidirectional" type="xs:string" />
  <xs:element name="availableForSearch" type="xs:boolean" />
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="definition" minOccurs="1" maxOccurs="1" />
        <xs:element ref="bidirectional" minOccurs="0" maxOccurs="1" />
        <xs:element ref="availableForSearch" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="long" />
  <xs:element name="integer" />
  <xs:element name="double" />
  <xs:element name="boolean" />
  <xs:element name="datetime" />
  <xs:element name="encoding" type="xs:string" />
  <xs:element name="string">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mimeType" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="encoding" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="choice" type="xs:string"/>
  <xs:element name="enumeration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="choice" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="other">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mimeType" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="size" type="xs:integer" />
  <xs:element name="minSize" type="xs:integer" />
  <xs:element name="maxSize" type="xs:integer" />
  <xs:element name="collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="simple-value" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="minSize" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="maxSize" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="composition">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="field" minOccurs="1" maxOccurs="1" />
          <xs:element ref="content" minOccurs="1" maxOccurs="1" />
        </xs:choice>
        <xs:element ref="field" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="content" minOccurs="1" maxOccurs="1" />
          <xs:element ref="long" minOccurs="1" maxOccurs="1" />
          <xs:element ref="integer" minOccurs="1" maxOccurs="1" />
          <xs:element ref="double" minOccurs="1" maxOccurs="1" />
          <xs:element ref="boolean" minOccurs="1" maxOccurs="1" />
          <xs:element ref="datetime" minOccurs="1" maxOccurs="1" />
          <xs:element ref="string" minOccurs="1" maxOccurs="1" />
          <xs:element ref="enumeration" minOccurs="1" maxOccurs="1" />
          <xs:element ref="other" minOccurs="1" maxOccurs="1" />
          <xs:element ref="collection" minOccurs="1" maxOccurs="1" />
          <xs:element ref="composition" minOccurs="1" maxOccurs="1" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="simple-value">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="content" minOccurs="1" maxOccurs="1" />
          <xs:element ref="long" minOccurs="1" maxOccurs="1" />
          <xs:element ref="integer" minOccurs="1" maxOccurs="1" />
          <xs:element ref="double" minOccurs="1" maxOccurs="1" />
          <xs:element ref="boolean" minOccurs="1" maxOccurs="1" />
          <xs:element ref="datetime" minOccurs="1" maxOccurs="1" />
          <xs:element ref="string" minOccurs="1" maxOccurs="1" />
          <xs:element ref="enumeration" minOccurs="1" maxOccurs="1" />
          <xs:element ref="other" minOccurs="1" maxOccurs="1" />
          <xs:element ref="composition" minOccurs="1" maxOccurs="1" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="required" type="xs:boolean" />
  <xs:element name="internal">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="external" type="xs:string" />
  <xs:element name="uri">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="internal" minOccurs="1" maxOccurs="1" />
          <xs:element ref="external" minOccurs="1" maxOccurs="1" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="defType">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="ABSTRACT_TYPE" />
        <xs:enumeration value="ABSTRACT_COMPONENT" />
        <xs:enumeration value="CONCRETE_TYPE" />
        <xs:enumeration value="CONCRETE_COMPONENT" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:complexType name="validator">
    <xs:sequence>
      <xs:element ref="uri" minOccurs="1" maxOccurs="1" />
      <xs:element ref="params" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="validator" type="validator" />
  <xs:element name="validators">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="validator" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="resource">
    <xs:sequence>
      <xs:element ref="name" minOccurs="1" maxOccurs="1" />
      <xs:element ref="mimeType" minOccurs="1" maxOccurs="1" />
      <xs:element ref="uri" minOccurs="1" maxOccurs="1" />
      <xs:element ref="params" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="prioritizedResource">
    <xs:sequence>
      <xs:element ref="name" minOccurs="1" maxOccurs="1" />
      <xs:element ref="uri" minOccurs="1" maxOccurs="1" />
      <xs:element ref="params" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="variation" type="resource" />
  <xs:element name="key" type="xs:string" />
  <xs:element name="val" type="xs:string" />
  <xs:complexType name="param">
    <xs:sequence>
      <xs:element ref="key" minOccurs="1" maxOccurs="1" />
      <xs:element ref="val" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="param" type="param" />
  <xs:complexType name="params">
    <xs:sequence>
      <xs:element ref="param" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="params" type="params" />
  <xs:element name="parameterizedDisplayNames" type="params"/>
  <xs:element name="representation" type="resource" />
  <xs:element name="representations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="representation" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="coprocessor" type="prioritizedResource" />
  <xs:element name="coprocessors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coprocessor" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="read">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coprocessors" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="write">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coprocessors" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="content-co-processors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="read" minOccurs="0" maxOccurs="1" />
        <xs:element ref="write" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="variations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="variation" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tBoolean">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true" />
      <xs:enumeration value="false" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="index" type="tBoolean" />
  <xs:element name="store" type="tBoolean" />
  <xs:element name="boost" type="xs:string" />
  <xs:element name="search">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="index" minOccurs="1" maxOccurs="1" />
        <xs:element ref="store" minOccurs="0" maxOccurs="1" />
        <xs:element ref="boost" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="update-standalone" type="tBoolean" />
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="displayName" minOccurs="0" maxOccurs="1" />
        <xs:element ref="parameterizedDisplayNames" minOccurs="0" maxOccurs="1" />
        <xs:element ref="value" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="required" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="variations" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="validators" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="search" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="update-standalone" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="params" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="field" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parent" type="contentPointer" />
  <xs:element name="statusName" type="xs:string" />
  <xs:element name="primaryField" type="xs:string" />
  <xs:element name="status">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="statusName" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contentType">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1" />
        <xs:element ref="displayName" minOccurs="0" maxOccurs="1" />
        <xs:element ref="parameterizedDisplayNames" minOccurs="0" maxOccurs="1" />
        <xs:element ref="parent" minOccurs="0" maxOccurs="1" />
        <xs:element ref="defType" minOccurs="0" maxOccurs="1" />
        <xs:element ref="primaryField" minOccurs="0" maxOccurs="1" />
        <xs:element ref="fields" minOccurs="1" />
        <xs:element ref="status" minOccurs="0" maxOccurs="1" />
        <xs:element ref="representations" minOccurs="0" maxOccurs="1" />
        <xs:element ref="content-co-processors" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="namespace" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="contentTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contentType" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== smartKaisar/smart-cms/webservice-modules/smart-cms-client-impl/src/test/resources/contentcoprocessors/content-type-def-with-enum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
    Document   : content-type-def-1.xml
    Created on : September 25, 2009, 1:10 PM
    Author     : imyousuf
    Description:
        Test content type definition.
-->
<contentTypes  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
               xmlns='http://www.smartitengineering.com/smart-cms/content/content-type-schema'
               xsi:schemaLocation='http://www.smartitengineering.com/smart-cms/content/content-type-schema ../../../../../../api-modules/content-api-impl/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd'>
  <contentType namespace="enum">
    <name>ContentCoProcessorTest</name>
    <parameterizedDisplayNames>
      <param>
        <key>en-US</key>
        <val>Address (en-US)</val>
      </param>
    </parameterizedDisplayNames>
    <primaryField>zipCode</primaryField>
    <fields>
      <field>
        <name>zipCode</name>
        <displayName>Postal Code/Zip Code</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <required>true</required>
        <search>
          <index>true</index>
          <store>true</store>
        </search>
      </field>
      <field>
        <name>directEnumField</name>
        <value>
          <enumeration>
            <choice>1</choice>
            <choice>2</choice>
          </enumeration>
        </value>
      </field>
      <field>
        <name>collectiveEnumField</name>
        <value>
          <collection>
            <simple-value>
              <enumeration>
                <choice>3</choice>
                <choice>4</choice>
              </enumeration>
            </simple-value>
          </collection>
        </value>
      </field>
      <field>
        <name>compositedEnumField</name>
        <value>
          <composition>
            <field>
              <name>enumField</name>
              <value>
                <enumeration>
                  <choice>5</choice>
                  <choice>6</choice>
                </enumeration>
              </value>
            </field>
          </composition>
        </value>
      </field>
      <field>
        <name>collectiveCompositedEnumField</name>
        <value>
          <collection>
            <simple-value>
              <composition>
                <field>
                  <name>enumField</name>
                  <value>
                    <enumeration>
                      <choice>7</choice>
                      <choice>8</choice>
                    </enumeration>
                  </value>
                </field>
              </composition>
            </simple-value>
          </collection>
        </value>
      </field>
    </fields>
    <content-co-processors>
      <read>
        <coprocessors>
          <coprocessor>
            <name>testr</name>
            <uri>
              <internal>
                <name>test</name>
              </internal>
            </uri>
            <params>
              <param>
                <key>k</key>
                <val>v</val>
              </param>
            </params>
          </coprocessor>
          <coprocessor>
            <name>testr1</name>
            <uri>
              <internal>
                <name>test1</name>
              </internal>
            </uri>
            <params>
              <param>
                <key>k1</key>
                <val>v1</val>
              </param>
            </params>
          </coprocessor>
        </coprocessors>
      </read>
      <write>
        <coprocessors>
          <coprocessor>
            <name>testw</name>
            <uri>
              <internal>
                <name>test2</name>
              </internal>
            </uri>
            <params>
              <param>
                <key>k2</key>
                <val>v2</val>
              </param>
            </params>
          </coprocessor>
        </coprocessors>
      </write>
    </content-co-processors>
  </contentType>               
</contentTypes>

=== smartKaisar/smart-cms/spi-modules/content-spi-type-validators-impl/src/test/resources/content-type-def-shopping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
    Document   : content-type-def-product.xml
    Created on : September 25, 2009, 5:20 PM
    Author     : imyousuf
    Description:
        A sample content type definition in context of smart shopping
-->
<contentTypes xmlns="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.smartitengineering.com/smart-cms/content/content-type-schema ../../../../../api-modules/content-api-impl/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd">
  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Product</name>
    <fields>
      <field>
        <name>manufactureID</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <required>true</required>
      </field>
      <field>
        <name>name</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <required>true</required>
      </field>
      <field>
        <name>description</name>
        <value>
          <string>
            <mimeType>application/xml</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>enumTest</name>
        <value>
          <enumeration>
            <choice>1</choice>
            <choice>2</choice>
            <choice>3</choice>
          </enumeration>
        </value>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>withdrawn</statusName>
      <statusName>obselete</statusName>
    </status>
  </contentType>

  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Book</name>
    <parent>
      <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
      <typeName>Product</typeName>
    </parent>
    <fields>
      <field>
        <name>isbn</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <required>true</required>
      </field>
      <field>
        <name>publishers</name>
        <value>
          <collection>
            <simple-value>
              <content>
                <definition>
                  <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
                  <typeName>Publisher</typeName>
                </definition>
                <availableForSearch>true</availableForSearch>
              </content>
            </simple-value>
            <maxSize>30</maxSize>
          </collection>
        </value>
        <required>true</required>
      </field>
      <field>
        <name>authors</name>
        <value>
          <collection>
            <simple-value>
              <content>
                <definition>
                  <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
                  <typeName>Author</typeName>
                </definition>
                <bidirectional>books</bidirectional>
              </content>
            </simple-value>
          </collection>
        </value>
        <required>true</required>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>obselete</statusName>
    </status>
  </contentType>

  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Publisher</name>
    <fields>
      <field>
        <name>name</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <required>true</required>
      </field>
      <field>
        <name>publicationHouse</name>
        <value>
          <content>
            <definition>
              <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
              <typeName>PublicationHouse</typeName>
            </definition>
          </content>
        </value>
        <required>true</required>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>obselete</statusName>
    </status>
  </contentType>

  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>PublicationHouse</name>
    <fields>
      <field>
        <name>name</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <required>true</required>
      </field>
      <field>
        <name>adress</name>
        <value>
          <content>
            <definition>
              <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
              <typeName>Address</typeName>
            </definition>
          </content>
        </value>
        <required>true</required>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>obselete</statusName>
    </status>
  </contentType>

  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Address</name>
    <fields>
      <field>
        <name>streetAddress</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>state</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>city</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>country</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>zipCode</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
    </fields>
    <status>
      <statusName>published</statusName>
    </status>
  </contentType>
		
  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Author</name>
    <fields>
      <field>
        <name>name</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>books</name>
        <value>
          <collection>
            <simple-value>
              <content>
                <definition>
                  <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
                  <typeName>Book</typeName>
                </definition>
                <bidirectional>authors</bidirectional>
              </content>
            </simple-value>
          </collection>
        </value>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>published</statusName>
    </status>
    <content-co-processors>
      <read>
        <coprocessors>
          <coprocessor>
            <name>testr</name>
            <uri>
              <internal>
                <name>test</name>
              </internal>
            </uri>
            <params>
              <param>
                <key>k</key>
                <val>v</val>
              </param>
            </params>
          </coprocessor>
          <coprocessor>
            <name>testr1</name>
            <uri>
              <internal>
                <name>test1</name>
              </internal>
            </uri>
            <params>
              <param>
                <key>k1</key>
                <val>v1</val>
              </param>
            </params>
          </coprocessor>
        </coprocessors>
      </read>
      <write>
        <coprocessors>
          <coprocessor>
            <name>testw</name>
            <uri>
              <internal>
                <name>test2</name>
              </internal>
            </uri>
            <params>
              <param>
                <key>k2</key>
                <val>v2</val>
              </param>
            </params>
          </coprocessor>
        </coprocessors>
      </write>
    </content-co-processors>
  </contentType>
</contentTypes>
